### ISSUE TITLE
大佬 请教个问题

### ISSUE THREAD

**Issue by 756230883** [ITxiaoguang/FilePicker#2]
val intent = Intent(Intent.ACTION_GET_CONTENT)
                intent.setType("*/*")
                intent.addCategory(Intent.CATEGORY_OPENABLE)
                this.startActivityForResult(
                    Intent.createChooser(intent, "选择文件"),
                    FilePickerConst.REQUEST_CODE_ALL_TYPE

**Comment by 756230883** [comment]
上面那句代码 是项目里面打开 手机文件管理器的  为什么我原样复制到自己项目里  打开的效果  和您的这个项目打开的效果不一样呢  是还需要设置什么吗

**Comment by ITxiaoguang** [comment]
老铁，你复制少了两个 * 了,复制可不能马虎。
你这样试试
```kotlin
val intent = Intent(Intent.ACTION_GET_CONTENT)
intent.setType("*/*") //这里是  */* 
intent.addCategory(Intent.CATEGORY_OPENABLE)
this.startActivityForResult(
Intent.createChooser(intent, "选择文件"),
FilePickerConst.REQUEST_CODE_ALL_TYPE)
```

**Comment by 756230883** [comment]
不好意思大佬  我复制到这的时候  出错了

**Comment by 756230883** [comment]
Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
                intent.setType("*/*"); //这里是  */*
                intent.addCategory(Intent.CATEGORY_OPENABLE);
                startActivityForResult(
                        Intent.createChooser(intent, "选择文件"),
                        3000);
这是我的代码  java的   您的项目打开  左边定位到的是“最近”  我用这段代码打开定位的是“我的手机
”

**Comment by 756230883** [comment]
![e72bc00ab288204426bd895c16aa929](https://user-images.githubusercontent.com/9440937/183390193-c2b171b8-40eb-4fc5-9689-e998ec24d499.jpg)
![55b0e530f3227a4c309dbc6d62afde2](https://user-images.githubusercontent.com/9440937/183390204-d5f66e91-e705-4e3a-8175-e33f84df2df4.jpg)

**Comment by ITxiaoguang** [comment]
你的代码在我这边直接提示 “没有应用可执行此操作”，你试试其他机型看看。
